### ISSUE TITLE
[meta] Tracking cloud provider permissioning

### ISSUE THREAD

**Issue by parasj** [skyplane-project/skyplane#149]
- [ ] Common issues:
  - [x] Need a better configuration engine stored in `~/.skylark/config.json`
  - [x] Generated AWS keys should be stored in `~/.ssh/skylark`
  - [ ] SSH keys should be signed with a random hash stored in the config and all created instances should be tagged with that hash so multiple users can share a single AWS account
  - [ ] Tag all instances when they are in use and untag them after skylark runs
  - [ ] Automatically have gateways shut down. Upon provisioning, configure instances to terminate upon shutdown (`instance-initiated-shutdown-behavior terminate`).
  - [x] `skylark init` should support disabling specific cloud providers if users do not have access
- [ ] AWS:
  - [ ] Skylark should use its own IAM rather than using the user's
  - [ ] On skylark init, query for opt-in regions enabled and then disable them in AWS. No explicit list should be maintained.
  - [ ] Skylark should make a `skylark` VPC instead of using the default VPC
  - [x] Skylark should use ECS-optimized container images (fixed by #152)
- [x] GCP:
  - [x] Skylark should use Container OS optimized images (fixed by #153)
- [ ] Azure:
  - [x] config.json bugs
      - [x] related: #109 
      - [x] related: #168
      - [x] related: #165
  - [x] Use single skylark resource group instead of making a new resource group per VM #125 #146 
  - [ ] Can we reuse more resources if possible rather than recreating them?
  - [x] Azure storage permissions should automatically load instead of using pre-signed URLs #109 
  - [ ] Test updated Azure interface to debug whether it solves resource group reliability issues
