### ISSUE TITLE
Bug bash week tracker

### ISSUE THREAD

**Issue by parasj** [skyplane-project/skyplane#554]
* Core Skyplane architecture issues:
  - [ ] #316
  - [ ] @antonzabreyko #541
* P0 issues:
  - [x] @sarahwooders #510
  - [x] @sarahwooders #528
  - [x] @parasj #553
  - [ ] @ShishirPatil #548
* P1 issues:
  - [x] #491 
* P2 issues:
  - [x] @abiswal2001 @parasj #524
  - [x] @ShishirPatil #552
  - [ ] #558 
  - [ ] Deterministic setup via Conda (for Sky camp)
* Blocked
  - [ ] #482
* Minor UX issues:
  - [ ] #483
* Improving integration testing
  - [ ] Edge testing many files
  - [ ] Edge testing empty buckets
  - [ ] Edge testing public buckets
  - [ ] Integration testing multipart transfers
  - [ ] Disable metrics in CI
  - [ ] #559
* Documentation and release
  - [x] @parasj #512
  - [x] Release a 0.2.0 version after the bug bash

**Comment by ShishirPatil** [comment]
#548 should be P0 I think?

**Comment by parasj** [comment]
@ShishirPatil RE #548 Agreed, although there is some mechanism to stop a transfer and clean up VMs. Ideally, we should debug why this isn't working well. I assigned this to you, please take a look at why it's not triggering when you have a chance.

**Comment by parasj** [comment]
We've shipped the bug bash for 0.2, so am closing this issue.
