### ISSUE TITLE
[API] Meta tracker of API issues

### ISSUE THREAD

**Issue by parasj** [skyplane-project/skyplane#643]
Concurrent transfers:
- [x] Chunk IDs should be UUIDs to remove sequential query limits

Provisioning:
- [x] #657

Bugs:
- [ ] #674
- [ ] Test Sync! (it likely doesn't work)
- [x] [bug] DirectPlanner generates topologies with double the nodes as required
- [x] [bug, perf] Chunker is very slow (lists ~1 chunk per second)
- [x] [bug] Gateway errors out with `TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

Open questions:

- [ ] How are gateway logs copied?
- [x] How will usage metrics work? @JasonDing0401 
- [x] How do we configure the dataplane with global config options?

Pending integrations:

- [ ] CLI cp
- [ ] CLI sync
- [ ] Missing features for CLI: TBD
