### ISSUE TITLE
[meta] CLI migration to API

### ISSUE THREAD

**Issue by parasj** [skyplane-project/skyplane#707]
CLI main:
- [x] (in progress, @abiswal2001) Migrate tracker to hooks interface, then publish transfer stats
- [x] (in progress, @abiswal2001) Progress bar rendering
- [x] (todo, @abiswal2001) sync implementation

Later PRs:
- [ ] (todo) ILP support
- [ ] @parasj [bug] Deprovisioning bug https://github.com/skyplane-project/skyplane/issues/687
- [ ] (todo, @JasonDing0401 ) CLI usage tracking over the API
- [ ] (in progress, @JasonDing0401 ) Documentation + autodocs for the API
- [ ] (todo) Replicate random support

API:
- [ ] Show spinner for deprovisioning VMs to give users confidence that VMs have been cleaned up
- [ ] (todo, @abiswal2001) Copy gateway logs after a transfer
- [ ] (todo) estimate_cost

Deprovision:
- [ ] [bug] Fix interrupted deprovision with auto_deprovision

**Comment by parasj** [comment]
API:
- [ ] (todo) estimate_cost
